Network:
  epochs: 300
  batch_size: 64
  sample_batch_size: 128
  n_steps: 16 # timestep
  dataset: "CelebA"
  in_channels: 3
  data_path: "/data/zhan/CV_data/CelebA"
  lr: 0.001
  sample_layer_lr_times: 10
  n_class: None
  latent_dim: 128
  input_size: 64
  model: "ESVAE_large" # ESVAE or ESVAE_large
  k: 20 # multiplier of channel
  scheduled: true # whether to apply scheduled sampling
  loss_func: 'mmd' # mmd or kld
  mmd_type: 'rbf'
  mu: 0.0  # the mu of the normal distribution of the sampled latent vector in generating stage
  var: 1.0  # the mu of the normal distribution of the sampled latent vector in generating stage
  distance_lambda: 0.001

  